# -----------------------------
# Builder Stage
# -----------------------------
FROM golang:1.25.0 AS builder

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=amd64

RUN mkdir /common

COPY services/common /common

WORKDIR /app

# Copy Go modules first for caching
COPY services/api/go.mod services/api/go.sum ./

RUN go mod download

# Copy source code and build
COPY services/api .

RUN go build -ldflags="-s -w" -o api main.go

# -----------------------------
# Build Webhook Service
# -----------------------------
WORKDIR /webhook

# Copy webhook source
COPY services/webhook/go.mod services/webhook/go.sum ./
RUN go mod download

COPY services/webhook .

RUN go build -ldflags="-s -w" -o webhook main.go

# -----------------------------
# Final Stage
# -----------------------------
FROM debian:trixie-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        sudo \
        ocserv \
        ca-certificates \
        procps \
        gnutls-bin \
        iptables \
        openssl \
        less \
        dnsutils \
        jq \
        curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set working directory
WORKDIR /app

# Copy API binary and scripts
COPY --from=builder /app/api /usr/local/bin/api
COPY --from=builder /webhook/webhook /usr/local/bin/webhook

COPY scripts/ocserv_entrypoint.sh /entrypoint.sh
COPY scripts/ocserv_server.sh /server.sh

# Make binaries and scripts executable
RUN chmod +x /entrypoint.sh /server.sh /usr/local/bin/api /usr/local/bin/webhook

# Expose ports
EXPOSE 443/tcp 443/udp 8080 8888

# Volumes
VOLUME ["/etc/ocserv", "/usr/local/bin/db"]

# Run entrypoint as root (required for ocserv)
ENTRYPOINT ["/entrypoint.sh"]

# Default CMD
CMD ["/server.sh"]
