/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GroupUnsyncedGroup } from '../models';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { OcservGroupSyncGroupRequest } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * OcservUnsyncedGroupApi - axios parameter creator
 * @export
 */
export const OcservUnsyncedGroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ocserv Groups from file
         * @summary Ocserv Groups from file
         * @param {string} authorization Bearer TOKEN
         * @param {OcservGroupSyncGroupRequest} request list of groups with config to sync in db
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsSyncPost: async (authorization: string, request: OcservGroupSyncGroupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservGroupsSyncPost', 'authorization', authorization)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('ocservGroupsSyncPost', 'request', request)
            const localVarPath = `/ocserv/groups/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * list of Unsynced Groups
         * @summary list of Unsynced Groups
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsUnsyncedGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservGroupsUnsyncedGet', 'authorization', authorization)
            const localVarPath = `/ocserv/groups/unsynced`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OcservUnsyncedGroupApi - functional programming interface
 * @export
 */
export const OcservUnsyncedGroupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OcservUnsyncedGroupApiAxiosParamCreator(configuration)
    return {
        /**
         * Ocserv Groups from file
         * @summary Ocserv Groups from file
         * @param {string} authorization Bearer TOKEN
         * @param {OcservGroupSyncGroupRequest} request list of groups with config to sync in db
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservGroupsSyncPost(authorization: string, request: OcservGroupSyncGroupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservGroupsSyncPost(authorization, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservUnsyncedGroupApi.ocservGroupsSyncPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * list of Unsynced Groups
         * @summary list of Unsynced Groups
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservGroupsUnsyncedGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GroupUnsyncedGroup>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservGroupsUnsyncedGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservUnsyncedGroupApi.ocservGroupsUnsyncedGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OcservUnsyncedGroupApi - factory interface
 * @export
 */
export const OcservUnsyncedGroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OcservUnsyncedGroupApiFp(configuration)
    return {
        /**
         * Ocserv Groups from file
         * @summary Ocserv Groups from file
         * @param {OcservUnsyncedGroupApiOcservGroupsSyncPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsSyncPost(requestParameters: OcservUnsyncedGroupApiOcservGroupsSyncPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<string>> {
            return localVarFp.ocservGroupsSyncPost(requestParameters.authorization, requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * list of Unsynced Groups
         * @summary list of Unsynced Groups
         * @param {OcservUnsyncedGroupApiOcservGroupsUnsyncedGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservGroupsUnsyncedGet(requestParameters: OcservUnsyncedGroupApiOcservGroupsUnsyncedGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<GroupUnsyncedGroup>> {
            return localVarFp.ocservGroupsUnsyncedGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for ocservGroupsSyncPost operation in OcservUnsyncedGroupApi.
 * @export
 * @interface OcservUnsyncedGroupApiOcservGroupsSyncPostRequest
 */
export interface OcservUnsyncedGroupApiOcservGroupsSyncPostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservUnsyncedGroupApiOcservGroupsSyncPost
     */
    readonly authorization: string

    /**
     * list of groups with config to sync in db
     * @type {OcservGroupSyncGroupRequest}
     * @memberof OcservUnsyncedGroupApiOcservGroupsSyncPost
     */
    readonly request: OcservGroupSyncGroupRequest
}

/**
 * Request parameters for ocservGroupsUnsyncedGet operation in OcservUnsyncedGroupApi.
 * @export
 * @interface OcservUnsyncedGroupApiOcservGroupsUnsyncedGetRequest
 */
export interface OcservUnsyncedGroupApiOcservGroupsUnsyncedGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservUnsyncedGroupApiOcservGroupsUnsyncedGet
     */
    readonly authorization: string
}

/**
 * OcservUnsyncedGroupApi - object-oriented interface
 * @export
 * @class OcservUnsyncedGroupApi
 * @extends {BaseAPI}
 */
export class OcservUnsyncedGroupApi extends BaseAPI {
    /**
     * Ocserv Groups from file
     * @summary Ocserv Groups from file
     * @param {OcservUnsyncedGroupApiOcservGroupsSyncPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservUnsyncedGroupApi
     */
    public ocservGroupsSyncPost(requestParameters: OcservUnsyncedGroupApiOcservGroupsSyncPostRequest, options?: RawAxiosRequestConfig) {
        return OcservUnsyncedGroupApiFp(this.configuration).ocservGroupsSyncPost(requestParameters.authorization, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * list of Unsynced Groups
     * @summary list of Unsynced Groups
     * @param {OcservUnsyncedGroupApiOcservGroupsUnsyncedGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservUnsyncedGroupApi
     */
    public ocservGroupsUnsyncedGet(requestParameters: OcservUnsyncedGroupApiOcservGroupsUnsyncedGetRequest, options?: RawAxiosRequestConfig) {
        return OcservUnsyncedGroupApiFp(this.configuration).ocservGroupsUnsyncedGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

